name: Shopify Lighthouse CI
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lighthouse
      uses: shopify/lighthouse-ci-action@v1
      with:
        access_token: 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
        store: nerd-app-testing.myshopify.com
        password: password
